import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar"
import Providers from '@/app/Providers';
import CallRenderer from '@/components/main/chatbox/calls/CallRenderer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HUGINN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative dark`}
      >
        <Providers>
          <AppSidebar />
          <main className=" w-screen ml-[-256.5px] col-span-1">
            <CallRenderer />
            {children}
          </main>
        </Providers>
    </body>
    </html>
  );
}
